/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#f6f3f5",
        "surface-container-high": "#1f1f22",
        "secondary": "#26fedc",
        "on-tertiary-fixed-variant": "#526900",
        "surface-container": "#19191c",
        "secondary-container": "#006b5b",
        "primary": "#d095ff",
        "primary-fixed": "#c782ff",
        "primary-fixed-dim": "#bd6efe",
        "on-background": "#f6f3f5",
        "surface-variant": "#262528",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "secondary-dim": "#00efce",
        "surface-container-lowest": "#000000",
        "on-secondary": "#005d4f",
        "on-secondary-fixed": "#00483d",
        "background": "#0e0e10",
        "surface-bright": "#2c2c2f",
        "surface-tint": "#d095ff",
        "outline-variant": "#48474a",
        "on-primary-container": "#38005e",
        "on-tertiary-fixed": "#3a4a00",
        "surface-container-low": "#131315",
        "secondary-fixed-dim": "#00efce",
        "on-primary-fixed-variant": "#450073",
        "on-tertiary": "#516700",
        "error-container": "#a70138",
        "on-surface-variant": "#acaaad",
        "inverse-surface": "#fcf8fb",
        "error": "#ff6e84",
        "on-primary": "#490078",
        "on-secondary-fixed-variant": "#006859",
        "tertiary-container": "#cafd00",
        "primary-dim": "#c57eff",
        "primary-container": "#c782ff",
        "surface-container-highest": "#262528",
        "on-tertiary-container": "#4a5e00",
        "outline": "#767577",
        "tertiary-fixed-dim": "#beee00",
        "on-secondary-container": "#ddfff5",
        "error-dim": "#d73357",
        "tertiary-dim": "#beee00",
        "surface-dim": "#0e0e10",
        "on-primary-fixed": "#000000",
        "inverse-primary": "#8534c4",
        "surface": "#0e0e10",
        "secondary-fixed": "#26fedc",
        "inverse-on-surface": "#555557",
        "tertiary-fixed": "#cafd00",
        "tertiary": "#f3ffca"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
